#########################################################################
# Title:         hetzner_server_ansible                                 #
# Author(s):     Patrice Le Guyader                                     #
# URL:           none                                                   #
# hetzner Image:   multiples                                            #
# --                                                                    #
#         Part of the hetzner ansible project:                          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: create Hetzner json informations files from Hetzner infrastructure.
  hosts: localhost
  # debugger: on_failed
  # vars_files:
  #   - vars.json
  #   - gitsecrets.yml
  vars:
    ansible_debug: true
  tasks:
    - name: Load the requested vars fro; json files
      ansible.builtin.set_fact:
        vars_file: "{{ lookup('file', 'vars.json') | from_json }}"
    - name: Showing content of vars.json
      ansible.builtin.debug:
        msg:
          - "-------------"
          - "{{ vars_file }}"
          - "-------------"
          - "{{ vars_file.hcloud_token }}"
          - "-------------"
      when: ansible_debug
    - name: defining variables.
      ansible.builtin.set_fact:
        api_token: "{{ vars_file.hcloud_token }}"
    - name: Load the JSON location file content
      hetzner.hcloud.hcloud_image_info:
      register: hcloud_image_info
    - name: Print the infos sended by the server
      debug:
        var: hcloud_image_info
    - name: Gather all images types
      ansible.builtin.set_fact:
        debian_images_list: "{{ hcloud_image_info.hcloud_image_info | selectattr('os_flavor','eq','debian')|map(attribute='name')|join(',') }}"
        centos_images_list: "{{ hcloud_image_info.hcloud_image_info | selectattr('os_flavor','eq','centos')|map(attribute='name')|join(',') }}"
        ubuntu_images_list: "{{ hcloud_image_info.hcloud_image_info | selectattr('os_flavor','eq','ubuntu')|map(attribute='name')|join(',') }}"
        fedora_images_list: "{{ hcloud_image_info.hcloud_image_info | selectattr('os_flavor','eq','fedora')|map(attribute='name')|join(',') }}"
    - name: Debugging all images types
      ansible.builtin.debug:
        msg:
          - '--------------------'
          - "{{ debian_images_list }}"
          - '--------------------'
          - "{{ centos_images_list }}"
          - '--------------------'
          - "{{ ubuntu_images_list }}"
          - '--------------------'
          - "{{ fedora_images_list }}"
          - '--------------------'
      # when: ansible_debug
    - name: Gather hcloud isos type infos
      hetzner.hcloud.hcloud_isos_info:
        # name: "pfSense-CE-2.6.0-RELEASE-amd64.iso"
        id: 12164
      register: output
    
    - name: Print the gathered infos
      debug:
        var: output.hcloud_isos_info