#########################################################################
# Title:         hetzner_server_ansible                                 #
# Author(s):     Patrice Le Guyader                                     #
# URL:           none                                                   #
# Docker Image:  multiples                                              #
# --                                                                    #
#         Part of the hetzner ansible project:                          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Read Hetzner informations from json data files.
  hosts: localhost
  vars:
    ansible_debug: true
  tasks:
    - name: Load the JSON location file content
      set_fact:
        hetzner_location: "{{ lookup('file', 'vars/hetzner-location-list.json') | from_json }}"
    - debug:
        var: hetzner_location
    - debug:
        msg: "{{ hetzner_location | community.general.json_query(query) | first }}"
      vars:
        location_name: Helsinki
        query: "[?city == '{{ location_name }}'].description"

    # - name: Display the JSON location file content
    #   shell: cat vars/hetzner-location-list.json
    #   register: location_result
    # - name: save the Json data to a Variable as a Fact
    #   set_fact:
    #     jsondata: "{{ location_result.stdout | from_json }}"

    # - name: setDomainName
    #   set_fact:
    #     domain_name: "{{ jsondata | json_query(jmesquery) }}"
    #   vars:
    #     jmesquery: 'domain.name'

#    - name: Debug the values
#      debug: msg=" Admin Listen Port => {{ admin_ListenPort }}, DomainName => {{ domain_name }}, DomainUserName => {{ domain_username }} , Domain Password => {{ domain_password }}"
#      when: ansible_debug