---
- name: Gathering server type informations
  hetzner.hcloud.hcloud_server_type_info:
  register: hcloud_server_type_infos

- name: Gathering all servers types
  ansible.builtin.set_fact:
    # no_log: false
    all_server_types: "{{ hcloud_server_type_infos.hcloud_server_type_info | map(attribute='name') }}"
    # all_server_types: "{{ hcloud_server_type_infos.hcloud_server_type_info | map(attribute='name') | join(',') }}"

- name: Lauching server_types_info.yml
  ansible.builtin.set_fact:
    no_log: false
    server_types_"{{ item.1 }}": "{{ 'server_types_'.+item.1 | default({}) + [{'name': item.0.name, 'vm_type': item.0.name, 'vm_cores': item.0.cores, 'vm_memory': item.0.memory, 'vm_disk': item.0.disk }] }}"
#    servers_types: all_server_types.split(',')
  loop:
    - "{{ hcloud_server_type_infos.hcloud_server_type_info|json_query('[].path') }}"
    # - "{{ hcloud_server_type_infos.hcloud_server_type_info|subelements(all_server_types) }}"
  # vars:
  #   my_var: "{{ lookup('vars', all_server_types) }}"
    # my_var: "{{ lookup('vars', all_server_types.split(',')) }}"

# - name: with_subelements -> loop
#   ansible.builtin.debug:
#     msg: "{{ item.0.name }} - {{ item.1 }}"
#   loop: "{{ hcloud_server_type_infos.hcloud_server_type_info|subelements('servers_types') }}"

# - name: Debugging Server types information
#   ansible.builtin.debug:
#     msg:
#       - '--------------------'
#       - "{{ windows_isos_list }}"
#       - '--------------------'
#   when: ansible_debug