---
- name: Gathering server type informations
  hetzner.hcloud.hcloud_server_type_info:
  register: hcloud_server_type_infos
- name: Lauching server_types_info.yml
  ansible.builtin.set_fact:
    set_log: true
    server_types_"{{ loop_var }}": "{{ server_types_.+loop_var | default({}) + [{'name': item.name, 'vm_type': item.name, 'vm_cores': item.cores, 'vm_memory': item.memory, 'vm_disk': item.disk }] }}"
  loop: 
    - "{{ hcloud_server_type_infos | selectattr('name','eq', loop_var) }}"