---
- name: Gather hcloud datacenter information
  no_log: true
  hetzner.hcloud.hcloud_datacenter_info:
  register: hcloud_datacenter_info

- name: Debugging datacenter informations
  ansible.builtin.debug:
    msg:
      - '--------------------'
      - "{{ hcloud_datacenter_info }}"
      - '--------------------'
  when: ansible_debug